# Generated by Django 5.1.6 on 2025-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_alter_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
