# Generated by Django 5.1.6 on 2025-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_remove_productuser_phone_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
