# Generated by Django 5.1.6 on 2025-02-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0004_alter_log_product_alter_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventoryApp.productuser'),
        ),
    ]
