# Generated by Django 5.1.6 on 2025-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0006_productuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
